---
version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{ checksum "package-lock.json"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: .circleci/greenkeeper
      - run: ./bin/run --version
      - run: ./bin/run --help
      - run:
          name: Testing
          command: npm test
      - run:
          name: Submitting code coverage to codecov
          command: |
            ./node_modules/.bin/nyc report --reporter text-lcov > coverage.lcov
            curl -s https://codecov.io/bash | bash
  node-8:
    <<: *test
    docker:
      - image: node:8
  release:
    <<: *test
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache: *restore_cache
      - run:
          name: Install dependencies
          command: |
            npm install -g @oclif/semantic-release@3 semantic-release@15
            npm install
      - run:
          name: Cutting release
          command: |
            semantic-release -e @oclif/semantic-release
      - save_cache:
          key: v1-yarn-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - ~/.npm
            - /usr/local/lib/node_modules

workflows:
  version: 2
  "@rocket.chat/apps-cli":
    jobs:
      - node-latest
      - node-8
      - release:
          context: org-global
          filters:
            branches: {only: master}
          requires:
            - node-latest
            - node-8
